CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Patients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "OIB" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Gender" text NOT NULL,
    "PatientNumber" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "Examinations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "ExaminationDateTime" timestamp with time zone NOT NULL,
    "ExaminationType" text NOT NULL,
    "Notes" text NOT NULL,
    CONSTRAINT "PK_Examinations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Examinations_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicalHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "DiseaseName" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    CONSTRAINT "PK_MedicalHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicalHistories_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Prescriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "MedicineName" text NOT NULL,
    "Dosage" text NOT NULL,
    "PrescriptionDate" timestamp with time zone NOT NULL,
    "Instructions" text NOT NULL,
    CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prescriptions_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ExaminationImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExaminationId" integer NOT NULL,
    "ImagePath" text NOT NULL,
    "UploadDateTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExaminationImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExaminationImages_Examinations_ExaminationId" FOREIGN KEY ("ExaminationId") REFERENCES "Examinations" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ExaminationImages_ExaminationId" ON "ExaminationImages" ("ExaminationId");

CREATE INDEX "IX_Examinations_PatientId" ON "Examinations" ("PatientId");

CREATE INDEX "IX_MedicalHistories_PatientId" ON "MedicalHistories" ("PatientId");

CREATE INDEX "IX_Prescriptions_PatientId" ON "Prescriptions" ("PatientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250203175931_InitialMigration', '9.0.1');

ALTER TABLE "Prescriptions" ALTER COLUMN "PrescriptionDate" TYPE timestamp without time zone;

ALTER TABLE "Patients" ALTER COLUMN "DateOfBirth" TYPE timestamp without time zone;

ALTER TABLE "Patients" ADD "PatientNumber2" text NOT NULL DEFAULT '';

ALTER TABLE "MedicalHistories" ALTER COLUMN "StartDate" TYPE timestamp without time zone;

ALTER TABLE "MedicalHistories" ALTER COLUMN "EndDate" TYPE timestamp without time zone;

ALTER TABLE "Examinations" ALTER COLUMN "ExaminationDateTime" TYPE timestamp without time zone;

ALTER TABLE "ExaminationImages" ALTER COLUMN "UploadDateTime" TYPE timestamp without time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209154455_AddPatientNumberToPatient', '9.0.1');

ALTER TABLE "Patients" DROP COLUMN "PatientNumber2";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209154719_Fixes', '9.0.1');

CREATE UNIQUE INDEX "IX_Patients_OIB" ON "Patients" ("OIB");

CREATE UNIQUE INDEX "IX_Patients_PatientNumber" ON "Patients" ("PatientNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209155409_AddedUniqueness', '9.0.1');

ALTER TABLE "Examinations" DROP COLUMN "LOLOLOL";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209162353_XY', '9.0.1');

ALTER TABLE "Examinations" DROP COLUMN "LOLOLOL";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209163117_RemovingObsoleteColumns', '9.0.1');

UPDATE "MedicalHistories" SET "EndDate" = TIMESTAMP '-infinity' WHERE "EndDate" IS NULL;
ALTER TABLE "MedicalHistories" ALTER COLUMN "EndDate" SET NOT NULL;
ALTER TABLE "MedicalHistories" ALTER COLUMN "EndDate" SET DEFAULT TIMESTAMP '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209164044_RequiredandUnique', '9.0.1');

ALTER TABLE "MedicalHistories" ALTER COLUMN "EndDate" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250209164427_RequiredandUniqueFix', '9.0.1');

DELETE FROM "Examinations"
WHERE "Id" = 1;

DELETE FROM "Examinations"
WHERE "Id" = 2;

DELETE FROM "Examinations"
WHERE "Id" = 3;

DELETE FROM "Examinations"
WHERE "Id" = 4;

DELETE FROM "Examinations"
WHERE "Id" = 5;

DELETE FROM "MedicalHistories"
WHERE "Id" = 1;

DELETE FROM "MedicalHistories"
WHERE "Id" = 2;

DELETE FROM "MedicalHistories"
WHERE "Id" = 3;

DELETE FROM "MedicalHistories"
WHERE "Id" = 4;

DELETE FROM "MedicalHistories"
WHERE "Id" = 5;

DELETE FROM "Prescriptions"
WHERE "Id" = 1;

DELETE FROM "Prescriptions"
WHERE "Id" = 2;

DELETE FROM "Prescriptions"
WHERE "Id" = 3;

DELETE FROM "Prescriptions"
WHERE "Id" = 4;

DELETE FROM "Prescriptions"
WHERE "Id" = 5;

DELETE FROM "Patients"
WHERE "Id" = 1;

DELETE FROM "Patients"
WHERE "Id" = 2;

DELETE FROM "Patients"
WHERE "Id" = 3;

DELETE FROM "Patients"
WHERE "Id" = 4;

DELETE FROM "Patients"
WHERE "Id" = 5;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250210220024_Clean', '9.0.1');

INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (1, TIMESTAMP '1989-01-01T00:00:00', 'PatientFirst1', 'Male', 'PatientLast1', '10000000001', 'P001');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (2, TIMESTAMP '1988-01-01T00:00:00', 'PatientFirst2', 'Female', 'PatientLast2', '10000000002', 'P002');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (3, TIMESTAMP '1987-01-01T00:00:00', 'PatientFirst3', 'Male', 'PatientLast3', '10000000003', 'P003');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (4, TIMESTAMP '1986-01-01T00:00:00', 'PatientFirst4', 'Female', 'PatientLast4', '10000000004', 'P004');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (5, TIMESTAMP '1985-01-01T00:00:00', 'PatientFirst5', 'Male', 'PatientLast5', '10000000005', 'P005');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (6, TIMESTAMP '1984-01-01T00:00:00', 'PatientFirst6', 'Female', 'PatientLast6', '10000000006', 'P006');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (7, TIMESTAMP '1983-01-01T00:00:00', 'PatientFirst7', 'Male', 'PatientLast7', '10000000007', 'P007');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (8, TIMESTAMP '1982-01-01T00:00:00', 'PatientFirst8', 'Female', 'PatientLast8', '10000000008', 'P008');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (9, TIMESTAMP '1981-01-01T00:00:00', 'PatientFirst9', 'Male', 'PatientLast9', '10000000009', 'P009');
INSERT INTO "Patients" ("Id", "DateOfBirth", "FirstName", "Gender", "LastName", "OIB", "PatientNumber")
VALUES (10, TIMESTAMP '1980-01-01T00:00:00', 'PatientFirst10', 'Female', 'PatientLast10', '10000000010', 'P0010');

INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (1, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (2, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (3, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (4, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (5, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (6, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (7, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (8, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (9, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (10, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 1);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (11, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (12, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (13, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (14, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (15, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (16, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (17, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (18, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (19, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (20, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 2);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (21, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (22, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (23, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (24, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (25, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (26, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (27, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (28, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (29, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (30, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 3);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (31, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (32, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (33, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (34, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (35, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (36, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (37, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (38, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (39, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (40, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 4);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (41, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (42, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (43, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (44, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (45, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (46, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (47, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (48, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (49, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (50, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 5);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (51, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (52, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (53, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (54, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (55, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (56, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (57, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (58, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (59, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (60, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 6);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (61, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (62, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (63, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (64, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (65, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (66, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (67, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (68, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (69, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (70, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 7);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (71, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (72, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (73, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (74, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (75, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (76, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (77, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (78, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (79, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (80, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 8);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (81, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (82, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (83, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (84, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (85, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (86, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (87, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (88, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (89, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (90, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 9);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (91, TIMESTAMP '2019-12-22T00:00:00', 'GP', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (92, TIMESTAMP '2019-12-12T00:00:00', 'KRV', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (93, TIMESTAMP '2019-12-02T00:00:00', 'X-RAY', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (94, TIMESTAMP '2019-11-22T00:00:00', 'CT', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (95, TIMESTAMP '2019-11-12T00:00:00', 'MR', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (96, TIMESTAMP '2019-11-02T00:00:00', 'ULTRA', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (97, TIMESTAMP '2019-10-23T00:00:00', 'EKG', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (98, TIMESTAMP '2019-10-13T00:00:00', 'ECHO', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (99, TIMESTAMP '2019-10-03T00:00:00', 'EYE', 'Routine checkup', 10);
INSERT INTO "Examinations" ("Id", "ExaminationDateTime", "ExaminationType", "Notes", "PatientId")
VALUES (100, TIMESTAMP '2019-09-23T00:00:00', 'DERM', 'Routine checkup', 10);

INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (1, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 1, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (2, 'Diabetes', NULL, 1, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (3, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 1, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (4, 'Migraine', NULL, 1, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (5, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 1, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (6, 'Anemia', NULL, 1, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (7, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 1, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (8, 'Eczema', NULL, 1, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (9, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 1, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (10, 'Heart Disease', NULL, 1, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (11, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 2, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (12, 'Diabetes', NULL, 2, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (13, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 2, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (14, 'Migraine', NULL, 2, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (15, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 2, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (16, 'Anemia', NULL, 2, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (17, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 2, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (18, 'Eczema', NULL, 2, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (19, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 2, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (20, 'Heart Disease', NULL, 2, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (21, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 3, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (22, 'Diabetes', NULL, 3, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (23, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 3, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (24, 'Migraine', NULL, 3, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (25, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 3, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (26, 'Anemia', NULL, 3, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (27, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 3, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (28, 'Eczema', NULL, 3, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (29, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 3, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (30, 'Heart Disease', NULL, 3, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (31, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 4, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (32, 'Diabetes', NULL, 4, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (33, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 4, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (34, 'Migraine', NULL, 4, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (35, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 4, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (36, 'Anemia', NULL, 4, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (37, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 4, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (38, 'Eczema', NULL, 4, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (39, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 4, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (40, 'Heart Disease', NULL, 4, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (41, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 5, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (42, 'Diabetes', NULL, 5, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (43, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 5, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (44, 'Migraine', NULL, 5, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (45, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 5, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (46, 'Anemia', NULL, 5, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (47, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 5, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (48, 'Eczema', NULL, 5, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (49, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 5, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (50, 'Heart Disease', NULL, 5, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (51, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 6, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (52, 'Diabetes', NULL, 6, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (53, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 6, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (54, 'Migraine', NULL, 6, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (55, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 6, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (56, 'Anemia', NULL, 6, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (57, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 6, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (58, 'Eczema', NULL, 6, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (59, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 6, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (60, 'Heart Disease', NULL, 6, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (61, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 7, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (62, 'Diabetes', NULL, 7, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (63, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 7, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (64, 'Migraine', NULL, 7, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (65, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 7, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (66, 'Anemia', NULL, 7, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (67, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 7, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (68, 'Eczema', NULL, 7, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (69, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 7, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (70, 'Heart Disease', NULL, 7, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (71, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 8, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (72, 'Diabetes', NULL, 8, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (73, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 8, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (74, 'Migraine', NULL, 8, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (75, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 8, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (76, 'Anemia', NULL, 8, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (77, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 8, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (78, 'Eczema', NULL, 8, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (79, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 8, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (80, 'Heart Disease', NULL, 8, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (81, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 9, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (82, 'Diabetes', NULL, 9, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (83, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 9, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (84, 'Migraine', NULL, 9, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (85, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 9, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (86, 'Anemia', NULL, 9, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (87, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 9, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (88, 'Eczema', NULL, 9, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (89, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 9, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (90, 'Heart Disease', NULL, 9, TIMESTAMP '2010-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (91, 'Hypertension', TIMESTAMP '2024-01-01T00:00:00', 10, TIMESTAMP '2019-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (92, 'Diabetes', NULL, 10, TIMESTAMP '2018-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (93, 'Asthma', TIMESTAMP '2022-01-01T00:00:00', 10, TIMESTAMP '2017-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (94, 'Migraine', NULL, 10, TIMESTAMP '2016-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (95, 'High Cholesterol', TIMESTAMP '2020-01-01T00:00:00', 10, TIMESTAMP '2015-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (96, 'Anemia', NULL, 10, TIMESTAMP '2014-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (97, 'Arthritis', TIMESTAMP '2018-01-01T00:00:00', 10, TIMESTAMP '2013-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (98, 'Eczema', NULL, 10, TIMESTAMP '2012-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (99, 'Chronic Bronchitis', TIMESTAMP '2016-01-01T00:00:00', 10, TIMESTAMP '2011-01-01T00:00:00');
INSERT INTO "MedicalHistories" ("Id", "DiseaseName", "EndDate", "PatientId", "StartDate")
VALUES (100, 'Heart Disease', NULL, 10, TIMESTAMP '2010-01-01T00:00:00');

INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (1, '5mg', 'Take as directed', 'Lisinopril', 1, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (2, '10mg', 'Take as directed', 'Metformin', 1, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (3, '15mg', 'Take as directed', 'Albuterol Inhaler', 1, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (4, '20mg', 'Take as directed', 'Sumatriptan', 1, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (5, '25mg', 'Take as directed', 'Atorvastatin', 1, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (6, '30mg', 'Take as directed', 'Ferrous Sulfate', 1, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (7, '35mg', 'Take as directed', 'Ibuprofen', 1, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (8, '40mg', 'Take as directed', 'Hydrocortisone Cream', 1, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (9, '45mg', 'Take as directed', 'Prednisone', 1, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (10, '50mg', 'Take as directed', 'Aspirin', 1, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (11, '5mg', 'Take as directed', 'Lisinopril', 2, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (12, '10mg', 'Take as directed', 'Metformin', 2, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (13, '15mg', 'Take as directed', 'Albuterol Inhaler', 2, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (14, '20mg', 'Take as directed', 'Sumatriptan', 2, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (15, '25mg', 'Take as directed', 'Atorvastatin', 2, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (16, '30mg', 'Take as directed', 'Ferrous Sulfate', 2, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (17, '35mg', 'Take as directed', 'Ibuprofen', 2, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (18, '40mg', 'Take as directed', 'Hydrocortisone Cream', 2, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (19, '45mg', 'Take as directed', 'Prednisone', 2, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (20, '50mg', 'Take as directed', 'Aspirin', 2, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (21, '5mg', 'Take as directed', 'Lisinopril', 3, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (22, '10mg', 'Take as directed', 'Metformin', 3, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (23, '15mg', 'Take as directed', 'Albuterol Inhaler', 3, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (24, '20mg', 'Take as directed', 'Sumatriptan', 3, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (25, '25mg', 'Take as directed', 'Atorvastatin', 3, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (26, '30mg', 'Take as directed', 'Ferrous Sulfate', 3, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (27, '35mg', 'Take as directed', 'Ibuprofen', 3, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (28, '40mg', 'Take as directed', 'Hydrocortisone Cream', 3, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (29, '45mg', 'Take as directed', 'Prednisone', 3, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (30, '50mg', 'Take as directed', 'Aspirin', 3, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (31, '5mg', 'Take as directed', 'Lisinopril', 4, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (32, '10mg', 'Take as directed', 'Metformin', 4, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (33, '15mg', 'Take as directed', 'Albuterol Inhaler', 4, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (34, '20mg', 'Take as directed', 'Sumatriptan', 4, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (35, '25mg', 'Take as directed', 'Atorvastatin', 4, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (36, '30mg', 'Take as directed', 'Ferrous Sulfate', 4, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (37, '35mg', 'Take as directed', 'Ibuprofen', 4, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (38, '40mg', 'Take as directed', 'Hydrocortisone Cream', 4, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (39, '45mg', 'Take as directed', 'Prednisone', 4, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (40, '50mg', 'Take as directed', 'Aspirin', 4, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (41, '5mg', 'Take as directed', 'Lisinopril', 5, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (42, '10mg', 'Take as directed', 'Metformin', 5, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (43, '15mg', 'Take as directed', 'Albuterol Inhaler', 5, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (44, '20mg', 'Take as directed', 'Sumatriptan', 5, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (45, '25mg', 'Take as directed', 'Atorvastatin', 5, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (46, '30mg', 'Take as directed', 'Ferrous Sulfate', 5, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (47, '35mg', 'Take as directed', 'Ibuprofen', 5, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (48, '40mg', 'Take as directed', 'Hydrocortisone Cream', 5, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (49, '45mg', 'Take as directed', 'Prednisone', 5, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (50, '50mg', 'Take as directed', 'Aspirin', 5, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (51, '5mg', 'Take as directed', 'Lisinopril', 6, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (52, '10mg', 'Take as directed', 'Metformin', 6, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (53, '15mg', 'Take as directed', 'Albuterol Inhaler', 6, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (54, '20mg', 'Take as directed', 'Sumatriptan', 6, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (55, '25mg', 'Take as directed', 'Atorvastatin', 6, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (56, '30mg', 'Take as directed', 'Ferrous Sulfate', 6, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (57, '35mg', 'Take as directed', 'Ibuprofen', 6, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (58, '40mg', 'Take as directed', 'Hydrocortisone Cream', 6, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (59, '45mg', 'Take as directed', 'Prednisone', 6, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (60, '50mg', 'Take as directed', 'Aspirin', 6, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (61, '5mg', 'Take as directed', 'Lisinopril', 7, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (62, '10mg', 'Take as directed', 'Metformin', 7, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (63, '15mg', 'Take as directed', 'Albuterol Inhaler', 7, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (64, '20mg', 'Take as directed', 'Sumatriptan', 7, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (65, '25mg', 'Take as directed', 'Atorvastatin', 7, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (66, '30mg', 'Take as directed', 'Ferrous Sulfate', 7, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (67, '35mg', 'Take as directed', 'Ibuprofen', 7, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (68, '40mg', 'Take as directed', 'Hydrocortisone Cream', 7, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (69, '45mg', 'Take as directed', 'Prednisone', 7, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (70, '50mg', 'Take as directed', 'Aspirin', 7, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (71, '5mg', 'Take as directed', 'Lisinopril', 8, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (72, '10mg', 'Take as directed', 'Metformin', 8, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (73, '15mg', 'Take as directed', 'Albuterol Inhaler', 8, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (74, '20mg', 'Take as directed', 'Sumatriptan', 8, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (75, '25mg', 'Take as directed', 'Atorvastatin', 8, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (76, '30mg', 'Take as directed', 'Ferrous Sulfate', 8, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (77, '35mg', 'Take as directed', 'Ibuprofen', 8, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (78, '40mg', 'Take as directed', 'Hydrocortisone Cream', 8, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (79, '45mg', 'Take as directed', 'Prednisone', 8, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (80, '50mg', 'Take as directed', 'Aspirin', 8, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (81, '5mg', 'Take as directed', 'Lisinopril', 9, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (82, '10mg', 'Take as directed', 'Metformin', 9, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (83, '15mg', 'Take as directed', 'Albuterol Inhaler', 9, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (84, '20mg', 'Take as directed', 'Sumatriptan', 9, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (85, '25mg', 'Take as directed', 'Atorvastatin', 9, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (86, '30mg', 'Take as directed', 'Ferrous Sulfate', 9, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (87, '35mg', 'Take as directed', 'Ibuprofen', 9, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (88, '40mg', 'Take as directed', 'Hydrocortisone Cream', 9, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (89, '45mg', 'Take as directed', 'Prednisone', 9, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (90, '50mg', 'Take as directed', 'Aspirin', 9, TIMESTAMP '2019-03-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (91, '5mg', 'Take as directed', 'Lisinopril', 10, TIMESTAMP '2019-12-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (92, '10mg', 'Take as directed', 'Metformin', 10, TIMESTAMP '2019-11-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (93, '15mg', 'Take as directed', 'Albuterol Inhaler', 10, TIMESTAMP '2019-10-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (94, '20mg', 'Take as directed', 'Sumatriptan', 10, TIMESTAMP '2019-09-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (95, '25mg', 'Take as directed', 'Atorvastatin', 10, TIMESTAMP '2019-08-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (96, '30mg', 'Take as directed', 'Ferrous Sulfate', 10, TIMESTAMP '2019-07-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (97, '35mg', 'Take as directed', 'Ibuprofen', 10, TIMESTAMP '2019-06-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (98, '40mg', 'Take as directed', 'Hydrocortisone Cream', 10, TIMESTAMP '2019-05-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (99, '45mg', 'Take as directed', 'Prednisone', 10, TIMESTAMP '2019-04-01T00:00:00');
INSERT INTO "Prescriptions" ("Id", "Dosage", "Instructions", "MedicineName", "PatientId", "PrescriptionDate")
VALUES (100, '50mg', 'Take as directed', 'Aspirin', 10, TIMESTAMP '2019-03-01T00:00:00');

SELECT setval(
    pg_get_serial_sequence('"Patients"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Patients") + 1,
        nextval(pg_get_serial_sequence('"Patients"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Examinations"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Examinations") + 1,
        nextval(pg_get_serial_sequence('"Examinations"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"MedicalHistories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "MedicalHistories") + 1,
        nextval(pg_get_serial_sequence('"MedicalHistories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Prescriptions"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Prescriptions") + 1,
        nextval(pg_get_serial_sequence('"Prescriptions"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250210220945_SeedTest2', '9.0.1');

DELETE FROM "Examinations"
WHERE "Id" = 1;

DELETE FROM "Examinations"
WHERE "Id" = 2;

DELETE FROM "Examinations"
WHERE "Id" = 3;

DELETE FROM "Examinations"
WHERE "Id" = 4;

DELETE FROM "Examinations"
WHERE "Id" = 5;

DELETE FROM "Examinations"
WHERE "Id" = 6;

DELETE FROM "Examinations"
WHERE "Id" = 7;

DELETE FROM "Examinations"
WHERE "Id" = 8;

DELETE FROM "Examinations"
WHERE "Id" = 9;

DELETE FROM "Examinations"
WHERE "Id" = 10;

DELETE FROM "Examinations"
WHERE "Id" = 11;

DELETE FROM "Examinations"
WHERE "Id" = 12;

DELETE FROM "Examinations"
WHERE "Id" = 13;

DELETE FROM "Examinations"
WHERE "Id" = 14;

DELETE FROM "Examinations"
WHERE "Id" = 15;

DELETE FROM "Examinations"
WHERE "Id" = 16;

DELETE FROM "Examinations"
WHERE "Id" = 17;

DELETE FROM "Examinations"
WHERE "Id" = 18;

DELETE FROM "Examinations"
WHERE "Id" = 19;

DELETE FROM "Examinations"
WHERE "Id" = 20;

DELETE FROM "Examinations"
WHERE "Id" = 21;

DELETE FROM "Examinations"
WHERE "Id" = 22;

DELETE FROM "Examinations"
WHERE "Id" = 23;

DELETE FROM "Examinations"
WHERE "Id" = 24;

DELETE FROM "Examinations"
WHERE "Id" = 25;

DELETE FROM "Examinations"
WHERE "Id" = 26;

DELETE FROM "Examinations"
WHERE "Id" = 27;

DELETE FROM "Examinations"
WHERE "Id" = 28;

DELETE FROM "Examinations"
WHERE "Id" = 29;

DELETE FROM "Examinations"
WHERE "Id" = 30;

DELETE FROM "Examinations"
WHERE "Id" = 31;

DELETE FROM "Examinations"
WHERE "Id" = 32;

DELETE FROM "Examinations"
WHERE "Id" = 33;

DELETE FROM "Examinations"
WHERE "Id" = 34;

DELETE FROM "Examinations"
WHERE "Id" = 35;

DELETE FROM "Examinations"
WHERE "Id" = 36;

DELETE FROM "Examinations"
WHERE "Id" = 37;

DELETE FROM "Examinations"
WHERE "Id" = 38;

DELETE FROM "Examinations"
WHERE "Id" = 39;

DELETE FROM "Examinations"
WHERE "Id" = 40;

DELETE FROM "Examinations"
WHERE "Id" = 41;

DELETE FROM "Examinations"
WHERE "Id" = 42;

DELETE FROM "Examinations"
WHERE "Id" = 43;

DELETE FROM "Examinations"
WHERE "Id" = 44;

DELETE FROM "Examinations"
WHERE "Id" = 45;

DELETE FROM "Examinations"
WHERE "Id" = 46;

DELETE FROM "Examinations"
WHERE "Id" = 47;

DELETE FROM "Examinations"
WHERE "Id" = 48;

DELETE FROM "Examinations"
WHERE "Id" = 49;

DELETE FROM "Examinations"
WHERE "Id" = 50;

DELETE FROM "Examinations"
WHERE "Id" = 51;

DELETE FROM "Examinations"
WHERE "Id" = 52;

DELETE FROM "Examinations"
WHERE "Id" = 53;

DELETE FROM "Examinations"
WHERE "Id" = 54;

DELETE FROM "Examinations"
WHERE "Id" = 55;

DELETE FROM "Examinations"
WHERE "Id" = 56;

DELETE FROM "Examinations"
WHERE "Id" = 57;

DELETE FROM "Examinations"
WHERE "Id" = 58;

DELETE FROM "Examinations"
WHERE "Id" = 59;

DELETE FROM "Examinations"
WHERE "Id" = 60;

DELETE FROM "Examinations"
WHERE "Id" = 61;

DELETE FROM "Examinations"
WHERE "Id" = 62;

DELETE FROM "Examinations"
WHERE "Id" = 63;

DELETE FROM "Examinations"
WHERE "Id" = 64;

DELETE FROM "Examinations"
WHERE "Id" = 65;

DELETE FROM "Examinations"
WHERE "Id" = 66;

DELETE FROM "Examinations"
WHERE "Id" = 67;

DELETE FROM "Examinations"
WHERE "Id" = 68;

DELETE FROM "Examinations"
WHERE "Id" = 69;

DELETE FROM "Examinations"
WHERE "Id" = 70;

DELETE FROM "Examinations"
WHERE "Id" = 71;

DELETE FROM "Examinations"
WHERE "Id" = 72;

DELETE FROM "Examinations"
WHERE "Id" = 73;

DELETE FROM "Examinations"
WHERE "Id" = 74;

DELETE FROM "Examinations"
WHERE "Id" = 75;

DELETE FROM "Examinations"
WHERE "Id" = 76;

DELETE FROM "Examinations"
WHERE "Id" = 77;

DELETE FROM "Examinations"
WHERE "Id" = 78;

DELETE FROM "Examinations"
WHERE "Id" = 79;

DELETE FROM "Examinations"
WHERE "Id" = 80;

DELETE FROM "Examinations"
WHERE "Id" = 81;

DELETE FROM "Examinations"
WHERE "Id" = 82;

DELETE FROM "Examinations"
WHERE "Id" = 83;

DELETE FROM "Examinations"
WHERE "Id" = 84;

DELETE FROM "Examinations"
WHERE "Id" = 85;

DELETE FROM "Examinations"
WHERE "Id" = 86;

DELETE FROM "Examinations"
WHERE "Id" = 87;

DELETE FROM "Examinations"
WHERE "Id" = 88;

DELETE FROM "Examinations"
WHERE "Id" = 89;

DELETE FROM "Examinations"
WHERE "Id" = 90;

DELETE FROM "Examinations"
WHERE "Id" = 91;

DELETE FROM "Examinations"
WHERE "Id" = 92;

DELETE FROM "Examinations"
WHERE "Id" = 93;

DELETE FROM "Examinations"
WHERE "Id" = 94;

DELETE FROM "Examinations"
WHERE "Id" = 95;

DELETE FROM "Examinations"
WHERE "Id" = 96;

DELETE FROM "Examinations"
WHERE "Id" = 97;

DELETE FROM "Examinations"
WHERE "Id" = 98;

DELETE FROM "Examinations"
WHERE "Id" = 99;

DELETE FROM "Examinations"
WHERE "Id" = 100;

DELETE FROM "MedicalHistories"
WHERE "Id" = 1;

DELETE FROM "MedicalHistories"
WHERE "Id" = 2;

DELETE FROM "MedicalHistories"
WHERE "Id" = 3;

DELETE FROM "MedicalHistories"
WHERE "Id" = 4;

DELETE FROM "MedicalHistories"
WHERE "Id" = 5;

DELETE FROM "MedicalHistories"
WHERE "Id" = 6;

DELETE FROM "MedicalHistories"
WHERE "Id" = 7;

DELETE FROM "MedicalHistories"
WHERE "Id" = 8;

DELETE FROM "MedicalHistories"
WHERE "Id" = 9;

DELETE FROM "MedicalHistories"
WHERE "Id" = 10;

DELETE FROM "MedicalHistories"
WHERE "Id" = 11;

DELETE FROM "MedicalHistories"
WHERE "Id" = 12;

DELETE FROM "MedicalHistories"
WHERE "Id" = 13;

DELETE FROM "MedicalHistories"
WHERE "Id" = 14;

DELETE FROM "MedicalHistories"
WHERE "Id" = 15;

DELETE FROM "MedicalHistories"
WHERE "Id" = 16;

DELETE FROM "MedicalHistories"
WHERE "Id" = 17;

DELETE FROM "MedicalHistories"
WHERE "Id" = 18;

DELETE FROM "MedicalHistories"
WHERE "Id" = 19;

DELETE FROM "MedicalHistories"
WHERE "Id" = 20;

DELETE FROM "MedicalHistories"
WHERE "Id" = 21;

DELETE FROM "MedicalHistories"
WHERE "Id" = 22;

DELETE FROM "MedicalHistories"
WHERE "Id" = 23;

DELETE FROM "MedicalHistories"
WHERE "Id" = 24;

DELETE FROM "MedicalHistories"
WHERE "Id" = 25;

DELETE FROM "MedicalHistories"
WHERE "Id" = 26;

DELETE FROM "MedicalHistories"
WHERE "Id" = 27;

DELETE FROM "MedicalHistories"
WHERE "Id" = 28;

DELETE FROM "MedicalHistories"
WHERE "Id" = 29;

DELETE FROM "MedicalHistories"
WHERE "Id" = 30;

DELETE FROM "MedicalHistories"
WHERE "Id" = 31;

DELETE FROM "MedicalHistories"
WHERE "Id" = 32;

DELETE FROM "MedicalHistories"
WHERE "Id" = 33;

DELETE FROM "MedicalHistories"
WHERE "Id" = 34;

DELETE FROM "MedicalHistories"
WHERE "Id" = 35;

DELETE FROM "MedicalHistories"
WHERE "Id" = 36;

DELETE FROM "MedicalHistories"
WHERE "Id" = 37;

DELETE FROM "MedicalHistories"
WHERE "Id" = 38;

DELETE FROM "MedicalHistories"
WHERE "Id" = 39;

DELETE FROM "MedicalHistories"
WHERE "Id" = 40;

DELETE FROM "MedicalHistories"
WHERE "Id" = 41;

DELETE FROM "MedicalHistories"
WHERE "Id" = 42;

DELETE FROM "MedicalHistories"
WHERE "Id" = 43;

DELETE FROM "MedicalHistories"
WHERE "Id" = 44;

DELETE FROM "MedicalHistories"
WHERE "Id" = 45;

DELETE FROM "MedicalHistories"
WHERE "Id" = 46;

DELETE FROM "MedicalHistories"
WHERE "Id" = 47;

DELETE FROM "MedicalHistories"
WHERE "Id" = 48;

DELETE FROM "MedicalHistories"
WHERE "Id" = 49;

DELETE FROM "MedicalHistories"
WHERE "Id" = 50;

DELETE FROM "MedicalHistories"
WHERE "Id" = 51;

DELETE FROM "MedicalHistories"
WHERE "Id" = 52;

DELETE FROM "MedicalHistories"
WHERE "Id" = 53;

DELETE FROM "MedicalHistories"
WHERE "Id" = 54;

DELETE FROM "MedicalHistories"
WHERE "Id" = 55;

DELETE FROM "MedicalHistories"
WHERE "Id" = 56;

DELETE FROM "MedicalHistories"
WHERE "Id" = 57;

DELETE FROM "MedicalHistories"
WHERE "Id" = 58;

DELETE FROM "MedicalHistories"
WHERE "Id" = 59;

DELETE FROM "MedicalHistories"
WHERE "Id" = 60;

DELETE FROM "MedicalHistories"
WHERE "Id" = 61;

DELETE FROM "MedicalHistories"
WHERE "Id" = 62;

DELETE FROM "MedicalHistories"
WHERE "Id" = 63;

DELETE FROM "MedicalHistories"
WHERE "Id" = 64;

DELETE FROM "MedicalHistories"
WHERE "Id" = 65;

DELETE FROM "MedicalHistories"
WHERE "Id" = 66;

DELETE FROM "MedicalHistories"
WHERE "Id" = 67;

DELETE FROM "MedicalHistories"
WHERE "Id" = 68;

DELETE FROM "MedicalHistories"
WHERE "Id" = 69;

DELETE FROM "MedicalHistories"
WHERE "Id" = 70;

DELETE FROM "MedicalHistories"
WHERE "Id" = 71;

DELETE FROM "MedicalHistories"
WHERE "Id" = 72;

DELETE FROM "MedicalHistories"
WHERE "Id" = 73;

DELETE FROM "MedicalHistories"
WHERE "Id" = 74;

DELETE FROM "MedicalHistories"
WHERE "Id" = 75;

DELETE FROM "MedicalHistories"
WHERE "Id" = 76;

DELETE FROM "MedicalHistories"
WHERE "Id" = 77;

DELETE FROM "MedicalHistories"
WHERE "Id" = 78;

DELETE FROM "MedicalHistories"
WHERE "Id" = 79;

DELETE FROM "MedicalHistories"
WHERE "Id" = 80;

DELETE FROM "MedicalHistories"
WHERE "Id" = 81;

DELETE FROM "MedicalHistories"
WHERE "Id" = 82;

DELETE FROM "MedicalHistories"
WHERE "Id" = 83;

DELETE FROM "MedicalHistories"
WHERE "Id" = 84;

DELETE FROM "MedicalHistories"
WHERE "Id" = 85;

DELETE FROM "MedicalHistories"
WHERE "Id" = 86;

DELETE FROM "MedicalHistories"
WHERE "Id" = 87;

DELETE FROM "MedicalHistories"
WHERE "Id" = 88;

DELETE FROM "MedicalHistories"
WHERE "Id" = 89;

DELETE FROM "MedicalHistories"
WHERE "Id" = 90;

DELETE FROM "MedicalHistories"
WHERE "Id" = 91;

DELETE FROM "MedicalHistories"
WHERE "Id" = 92;

DELETE FROM "MedicalHistories"
WHERE "Id" = 93;

DELETE FROM "MedicalHistories"
WHERE "Id" = 94;

DELETE FROM "MedicalHistories"
WHERE "Id" = 95;

DELETE FROM "MedicalHistories"
WHERE "Id" = 96;

DELETE FROM "MedicalHistories"
WHERE "Id" = 97;

DELETE FROM "MedicalHistories"
WHERE "Id" = 98;

DELETE FROM "MedicalHistories"
WHERE "Id" = 99;

DELETE FROM "MedicalHistories"
WHERE "Id" = 100;

DELETE FROM "Prescriptions"
WHERE "Id" = 1;

DELETE FROM "Prescriptions"
WHERE "Id" = 2;

DELETE FROM "Prescriptions"
WHERE "Id" = 3;

DELETE FROM "Prescriptions"
WHERE "Id" = 4;

DELETE FROM "Prescriptions"
WHERE "Id" = 5;

DELETE FROM "Prescriptions"
WHERE "Id" = 6;

DELETE FROM "Prescriptions"
WHERE "Id" = 7;

DELETE FROM "Prescriptions"
WHERE "Id" = 8;

DELETE FROM "Prescriptions"
WHERE "Id" = 9;

DELETE FROM "Prescriptions"
WHERE "Id" = 10;

DELETE FROM "Prescriptions"
WHERE "Id" = 11;

DELETE FROM "Prescriptions"
WHERE "Id" = 12;

DELETE FROM "Prescriptions"
WHERE "Id" = 13;

DELETE FROM "Prescriptions"
WHERE "Id" = 14;

DELETE FROM "Prescriptions"
WHERE "Id" = 15;

DELETE FROM "Prescriptions"
WHERE "Id" = 16;

DELETE FROM "Prescriptions"
WHERE "Id" = 17;

DELETE FROM "Prescriptions"
WHERE "Id" = 18;

DELETE FROM "Prescriptions"
WHERE "Id" = 19;

DELETE FROM "Prescriptions"
WHERE "Id" = 20;

DELETE FROM "Prescriptions"
WHERE "Id" = 21;

DELETE FROM "Prescriptions"
WHERE "Id" = 22;

DELETE FROM "Prescriptions"
WHERE "Id" = 23;

DELETE FROM "Prescriptions"
WHERE "Id" = 24;

DELETE FROM "Prescriptions"
WHERE "Id" = 25;

DELETE FROM "Prescriptions"
WHERE "Id" = 26;

DELETE FROM "Prescriptions"
WHERE "Id" = 27;

DELETE FROM "Prescriptions"
WHERE "Id" = 28;

DELETE FROM "Prescriptions"
WHERE "Id" = 29;

DELETE FROM "Prescriptions"
WHERE "Id" = 30;

DELETE FROM "Prescriptions"
WHERE "Id" = 31;

DELETE FROM "Prescriptions"
WHERE "Id" = 32;

DELETE FROM "Prescriptions"
WHERE "Id" = 33;

DELETE FROM "Prescriptions"
WHERE "Id" = 34;

DELETE FROM "Prescriptions"
WHERE "Id" = 35;

DELETE FROM "Prescriptions"
WHERE "Id" = 36;

DELETE FROM "Prescriptions"
WHERE "Id" = 37;

DELETE FROM "Prescriptions"
WHERE "Id" = 38;

DELETE FROM "Prescriptions"
WHERE "Id" = 39;

DELETE FROM "Prescriptions"
WHERE "Id" = 40;

DELETE FROM "Prescriptions"
WHERE "Id" = 41;

DELETE FROM "Prescriptions"
WHERE "Id" = 42;

DELETE FROM "Prescriptions"
WHERE "Id" = 43;

DELETE FROM "Prescriptions"
WHERE "Id" = 44;

DELETE FROM "Prescriptions"
WHERE "Id" = 45;

DELETE FROM "Prescriptions"
WHERE "Id" = 46;

DELETE FROM "Prescriptions"
WHERE "Id" = 47;

DELETE FROM "Prescriptions"
WHERE "Id" = 48;

DELETE FROM "Prescriptions"
WHERE "Id" = 49;

DELETE FROM "Prescriptions"
WHERE "Id" = 50;

DELETE FROM "Prescriptions"
WHERE "Id" = 51;

DELETE FROM "Prescriptions"
WHERE "Id" = 52;

DELETE FROM "Prescriptions"
WHERE "Id" = 53;

DELETE FROM "Prescriptions"
WHERE "Id" = 54;

DELETE FROM "Prescriptions"
WHERE "Id" = 55;

DELETE FROM "Prescriptions"
WHERE "Id" = 56;

DELETE FROM "Prescriptions"
WHERE "Id" = 57;

DELETE FROM "Prescriptions"
WHERE "Id" = 58;

DELETE FROM "Prescriptions"
WHERE "Id" = 59;

DELETE FROM "Prescriptions"
WHERE "Id" = 60;

DELETE FROM "Prescriptions"
WHERE "Id" = 61;

DELETE FROM "Prescriptions"
WHERE "Id" = 62;

DELETE FROM "Prescriptions"
WHERE "Id" = 63;

DELETE FROM "Prescriptions"
WHERE "Id" = 64;

DELETE FROM "Prescriptions"
WHERE "Id" = 65;

DELETE FROM "Prescriptions"
WHERE "Id" = 66;

DELETE FROM "Prescriptions"
WHERE "Id" = 67;

DELETE FROM "Prescriptions"
WHERE "Id" = 68;

DELETE FROM "Prescriptions"
WHERE "Id" = 69;

DELETE FROM "Prescriptions"
WHERE "Id" = 70;

DELETE FROM "Prescriptions"
WHERE "Id" = 71;

DELETE FROM "Prescriptions"
WHERE "Id" = 72;

DELETE FROM "Prescriptions"
WHERE "Id" = 73;

DELETE FROM "Prescriptions"
WHERE "Id" = 74;

DELETE FROM "Prescriptions"
WHERE "Id" = 75;

DELETE FROM "Prescriptions"
WHERE "Id" = 76;

DELETE FROM "Prescriptions"
WHERE "Id" = 77;

DELETE FROM "Prescriptions"
WHERE "Id" = 78;

DELETE FROM "Prescriptions"
WHERE "Id" = 79;

DELETE FROM "Prescriptions"
WHERE "Id" = 80;

DELETE FROM "Prescriptions"
WHERE "Id" = 81;

DELETE FROM "Prescriptions"
WHERE "Id" = 82;

DELETE FROM "Prescriptions"
WHERE "Id" = 83;

DELETE FROM "Prescriptions"
WHERE "Id" = 84;

DELETE FROM "Prescriptions"
WHERE "Id" = 85;

DELETE FROM "Prescriptions"
WHERE "Id" = 86;

DELETE FROM "Prescriptions"
WHERE "Id" = 87;

DELETE FROM "Prescriptions"
WHERE "Id" = 88;

DELETE FROM "Prescriptions"
WHERE "Id" = 89;

DELETE FROM "Prescriptions"
WHERE "Id" = 90;

DELETE FROM "Prescriptions"
WHERE "Id" = 91;

DELETE FROM "Prescriptions"
WHERE "Id" = 92;

DELETE FROM "Prescriptions"
WHERE "Id" = 93;

DELETE FROM "Prescriptions"
WHERE "Id" = 94;

DELETE FROM "Prescriptions"
WHERE "Id" = 95;

DELETE FROM "Prescriptions"
WHERE "Id" = 96;

DELETE FROM "Prescriptions"
WHERE "Id" = 97;

DELETE FROM "Prescriptions"
WHERE "Id" = 98;

DELETE FROM "Prescriptions"
WHERE "Id" = 99;

DELETE FROM "Prescriptions"
WHERE "Id" = 100;

DELETE FROM "Patients"
WHERE "Id" = 1;

DELETE FROM "Patients"
WHERE "Id" = 2;

DELETE FROM "Patients"
WHERE "Id" = 3;

DELETE FROM "Patients"
WHERE "Id" = 4;

DELETE FROM "Patients"
WHERE "Id" = 5;

DELETE FROM "Patients"
WHERE "Id" = 6;

DELETE FROM "Patients"
WHERE "Id" = 7;

DELETE FROM "Patients"
WHERE "Id" = 8;

DELETE FROM "Patients"
WHERE "Id" = 9;

DELETE FROM "Patients"
WHERE "Id" = 10;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250210221126_SeedRemove', '9.0.1');

COMMIT;

